### ISSUE TITLE
Issue with sethome command

### ISSUE THREAD

**Issue by EvanSchleret** [TechnoVisionDev/HomeGUI#3]
Hi ! Hope you're fine ;)

I obtain this error when I run sethome commande :

`[11:57:48] [Server thread/ERROR]: Unhandled exception executing command 'sethome' in plugin HomeGUI v1.3.1
org.bukkit.command.CommandException: Unhandled exception executing command 'sethome' in plugin HomeGUI v1.3.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:469) ~[?:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[?:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[?:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [server.jar:git-Spigot-cbd1a1b-009d8af]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: net.wesjd.anvilgui.AnvilGUI$Builder.item(Lorg/bukkit/inventory/ItemStack;)Lnet/wesjd/anvilgui/AnvilGUI$Builder;
at com.technovision.homegui.commands.SetHomeCommand.onCommand(SetHomeCommand.java:35) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-cbd1a1b-009d8af]
... 20 more`

In pastebin : https://pastebin.com/jT5W4tN7

Any idea ?

**Comment by TechnoVisionDev** [comment]
Thanks for the bug report! Unfortunately I am not getting the same result when running the sethome command. Do you mind providing a few details, like the **full console log pastebin**, your spigot jar type and version, and what exactly you did to get this error.

**Comment by EvanSchleret** [comment]
Hi,

Thanks for your answer !

I have no more log in the console for this plugin.
The spigot version : CraftBukkit version git-Spigot-cbd1a1b-009d8af (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT).

To get this error, I just type the command "sethome" from the game.
